# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: David Salvador-Jasin
email: dsalvadorjasin@turing.ac.uk
full_name: David Salvador-Jasin
github_organization: dsj976
keywords: rsecon24,python
license: Apachev2
package_name: baklava
package_short_description: Effortlessly creating Python packages with good practices
    - RSECon24
template_profile: minimum
version: 0.1.0
